name: Build Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: /tmp/myimage.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
      - name: Test Image
        run: echo "Test Passed"

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
      
      - name: Tag image with latest and build number
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          docker tag myimage:latest myregistry/myimage:latest
          docker tag myimage:latest myregistry/myimage:${GITHUB_RUN_NUMBER}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to registry
        run: |
          docker push myregistry/myimage:latest
          docker push myregistry/myimage:${GITHUB_RUN_NUMBER}
