name: Build Image

on:
  push:

env:
  DOCKER_DEMO_PROJECT_PATH: "projects/image-demo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKER_DEMO_PROJECT_PATH }}/.
          tags: mmn01/vdc-demo:latest
          outputs: type=docker,dest=/tmp/vdc-demo.tar
          push: false
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vdc-demo
          path: /tmp/vdc-demo.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vdc-demo
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/vdc-demo.tar
      - name: Check Image
        run: docker images
      - name: Test Image
        run: docker run mmn01/vdc-demo:latest

  # push:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: myimage
  #         path: /tmp
      
  #     - name: Load image
  #       run: |
  #         docker load --input /tmp/myimage.tar
      
  #     - name: Tag image with latest and build number
  #       env:
  #         GITHUB_RUN_NUMBER: ${{ github.run_number }}
  #       run: |
  #         docker tag myimage:latest myregistry/myimage:latest
  #         docker tag myimage:latest myregistry/myimage:${GITHUB_RUN_NUMBER}
      
  #     - name: Push Image to registry
  #       run: |
  #         docker images
  #     # - name: Login to Docker Hub
  #     #   uses: docker/login-action@v4
  #     #   with:
  #     #     username: ${{ vars.DOCKERHUB_USERNAME }}
  #     #     password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     # - name: Push image to registry
  #     #   run: |
  #     #     docker push myregistry/myimage:latest
  #     #     docker push myregistry/myimage:${GITHUB_RUN_NUMBER}
