name: Parallel

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_DEMO_PROJECT_PATH: "projects/python-demo"

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd $PYTHON_DEMO_PROJECT_PATH && pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          cd PYTHON_DEMO_PROJECT_PATH/src && ruff check --output-format=github .
        continue-on-error: false
  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd $PYTHON_DEMO_PROJECT_PATH && pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          cd PYTHON_DEMO_PROJECT_PATH/src && ruff format --check --diff --output-format=github .
        continue-on-error: false



  # test:
  #   runs-on: ubuntu-latest
  #   needs: ['format', 'lint']
  #   strategy:
  #     matrix:
  #       python-version: ['3.10', '3.11', '3.12']
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Test Python ${{ matrix.python-version }} 
  #       run: echo ${{ matrix.python-version }}
  
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: ['test']
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #     - name: Publish Build
  #       run: echo "Python App Published"
