name: Terraform Apply

on:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  dev:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/terraform-apply-action.yml
    with:
      vdc-environment: dev
      gh-environment: Dev
  live:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/terraform-apply-action.yml
    needs: dev
    with:
      vdc-environment: live
      gh-environment: Live