name: Terraform Plan

on:
  push:
  # pull_request:
  #   branches: ['main']

permissions:
  pull-requests: write

jobs:
  terraform_plan_dev:
    # uses: ./.github/workflows/terraform-plan-action.yml
    uses: ./.github/reusable/terraform-plan-action.yml
    with:
      vdc-environment: dev
  terraform_plan_live:
    # uses: ./.github/workflows/terraform-plan-action.yml
    uses: ./.github/reusable/terraform-plan-action.yml
    needs: terraform_plan_dev
    with:
      vdc-environment: live
