name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  dev:
    if: contains(github.event.head_commit.message, 'Merge pull request')
    uses: ./.github/workflows/terraform-apply-action.yml
    with:
      vdc-environment: dev
      gh-environment: Dev
  live:
    uses: ./.github/workflows/terraform-apply-action.yml
    needs: dev
    with:
      vdc-environment: live
      gh-environment: Live